apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    env: prod
spec:
  # type: LoadBalancer
  selector:
    app: nginx
    env: prod
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: nginx-svc-port