apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense
  labels:
    app: backend
    env: prod
data:
  DB_Host: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      env: prod
  template:
    metadata:
      labels:
        app: backend
        env: prod
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v7
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    env: prod
spec:
  selector:
    app: backend
    env: prod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: backend-svc-port
---
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: expense
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 15