apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    env: prod
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: mysql
      env: prod
  template:
    metadata:
      labels:
        app: mysql
        env: prod
    spec:
      containers:
        - name: mysql
          image: cekharch/mysql:{{ .Values.deployment.image.tag }}
          
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    env: prod
spec:
  selector:
    app: mysql
    env: prod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mysql-svc-port